[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#005b96"
font = "sans serif"
